global:
  scrape_interval: 5s # 5초마다 데이터 수집

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 도커 환경에서 호스트 컴퓨터에 접속하기 위해 host.docker.internal 사용
      - targets: ['host.docker.internal:8080']