spring:

  datasource:
    # 로컬 실행 시 localhost 사용, 도커 실행 시는 환경변수가 덮어씀
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2  # [설정 2] DB 커넥션 풀 크기 (기본값: 10)
      register-mbeans: true
      connection-timeout: 6000 # 30초 대기 후 에러 (변경 불필요)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  application:
    name: Reservation

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/delivery_db

  kafka:
    bootstrap-servers: localhost:9092 # 카프카 브로커 주소 (도커로 띄운 포트)

    listener:
      ack-mode: manual_immediate

    # [컨슈머(수신자) 설정]
    consumer:
      group-id: coupon-worker-group # 컨슈머 그룹 ID
      auto-offset-reset: earliest   # 초기 오프셋 설정 (가장 처음부터 읽음)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    # [프로듀서(발송자) 설정]
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  tomcat:
    threads:
      max: 200    # [설정 1] 톰캣 최대 2스레드 수 (기본값: 200)
      min-spare: 200
    mbean-registry:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      hikaricp: true
      tomcat: true
      http: true